sources:
  - name: fux
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/mike4751/fux-testing

plugins:
  - pollingLive:
      defaultInterval: 2000

documents:
  - ./graph/*.graphql
