sources:
  - name: fux
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/bitbeckers/fux-goerli

plugins:
  - pollingLive:
      defaultInterval: 2000

documents:
  - ./graph/*.graphql
